services:
  app:
    build: .
    container_name: github-search
    ports:
      - 5173:5173
    volumes:
      - .:/app
      - /app/node_modules

  storybook:
    build: 
      dockerfile: storybook.Dockerfile
    container_name: gs-storybook
    ports:
      - 6006:6006
    volumes:
      - .:/app
      - /app/node_modules
